feat: 랜덤 문제 추출, 시간초 기능, 라이프 기능 추가
team-Interviewers/team-Interviewers-FE pull request #12
Opened 2023-08-25 05:52 UTC by ww8007

## 📖 개요

- resolve : #11

## 💻 작업사항

1. 문제 레포 서브 모듈 방식으로 추가 [link](https://www.notion.so/interviewers/90f13e2413404e78a513c4cd1701b331?pvs=4)
2. 랜덤 문제 추출 기능 추가
3. 시간초 기능 추가
4. 라이프 기능 추가
5. 사용자 문제 입력 기능 추가

## 💡 작성한 이슈 외에 작업한 사항

- [x] Button UI 컴포넌트 추가
- [x] Select UI 컴포넌트 추가
- [x] 모달 관련 스타일 및 기능 수정
- [x] react-icons 라이브러리 추가

## ✔️ check list

- [x] 작성한 이슈의 내용을 전부 적용했나요?
- [x] 리뷰어를 등록했나요?

2023-08-25 13:50 UTC, pengooseDev requested changes

2023-08-25 13:50 UTC, pengooseDev commented on src/pages/content/components/IconWrapper.tsx
> +};
Container Pattern으로 구현하셨군요 :)
패턴의 이름을 따와서 IconContainer이라는 네이밍도 종종 사용하는 것 같습니다.

2023-08-25 13:50 UTC, pengooseDev commented on src/pages/content/components/Answer.tsx
> +};
문제의 type이 확장 가능한 부분이라 판단되면,  전역에서 사용할 수 있도록 type 폴더에서 관리하는 것도 좋을 것 같습니다 :)

```tsx
type QuestionType = 'objective' | 'subjective';

const isObjective = (question: Question): QuestionType  => {
  return question.choices.length > 0 ? 'objective' : 'subjective';
};
```

2023-08-25 13:50 UTC, pengooseDev commented on src/pages/content/components/Answer.tsx
> +};
문제의 type이 추가될 경우를 고려하여, 아래와 같이 작성할 수도 있을 것 같습니다 :) 

```tsx
const Answer = ({ answer, questionType, handleChange }: AnswerProps) => {
  const answerComponent = (questionType : QuestionType) => {
    if (questionType === QUESTION_TYPE.OBJECTIVE) 
        return <ObjectiveAnswer question={question} handleChange={handleChange} />

    if (questionType === QUESTION_TYPE.SUBJECTIVE) 
        return <SubjectiveAnswer answer={answer} handleChange={handleChange} />

    return null;
  }

  return (
    <Wrapper>
      {answerComponent(questionType)}
    </Wrapper>
  );
};

```

2023-08-25 13:50 UTC, pengooseDev commented on src/pages/content/utils/theme.ts
> +} as const;
theme 객체의 field를 관심사에 따라 분리하면 더 확장성이 높아질 것 같습니다. :)

```tsx
export const lightTheme = {
  colors: {
    default: '#161617',
  },
  background: {
    default: '#ffffff',
  },
  button: {
    primary: '#30B198',
    active: '#4DA48C',
    //inactivate: #hexCode;
  },
  palatte: {
    grey200: '#EEEEEE',
    grey400: '#BDBDBD',
    grey600: '#757575',
    grey700: '#616161',
    grey800: '#424242',
    grey850: '#303030',
    grey900: '#212121',
  }
} as const;
```

2023-08-25 13:50 UTC, pengooseDev commented on src/pages/content/components/Portal/Portal.tsx
> +  };
Portal Component에 Question의 비즈니스 로직이 합쳐져 결합도가 높아질 수 있지 않을까 생각합니다 :)
단일책임의 원칙의 관점에서 도메인에 따른 로직을 해당 컴포넌트 내부로 이동하는 것이 좋지않을까 생각합니다.

2023-08-27 13:27 UTC, ww8007 commented on src/pages/content/components/Portal/Portal.tsx
> +  };
흠 요게 각각의 컴포넌트 안으로 들어가게 되면 다른 컴포넌트에서 사용이 필요해질시 꺼내기가 힘들다는 점과 메인 비지니스 로직을 한 눈에 바라볼 수 있다는 점에서 다음과 같이 바깥에서 작성을 하였는데 이에 대해서는 어떻게 생각하시나요??

2023-08-27 13:27 UTC, ww8007 commented on src/pages/content/utils/theme.ts
> +} as const;
요게 더 깔끔 하겠네요! 수정해 보겠습니다 😃

2023-08-27 13:32 UTC, ww8007 commented on src/pages/content/components/IconWrapper.tsx
> +};
흠 아니면 children 자체를 button으로 감싼거니까 그냥 ButtonContainer라고 작성을 해볼까요? 생각해보니 children에는 무엇이든 들어갈 수 있어서 특정성을 보여주기가 어렵네요 🧐

2023-08-27 13:33 UTC, ww8007 commented on src/pages/content/components/Answer.tsx
> +};
넵 더 좋은 방식인거 같아요. 수정해보겠습니다 👍

2023-08-27 17:05 UTC, pengooseDev commented on src/pages/content/components/Portal/Portal.tsx
> +  };
그렇기 때문에 나누는 것이 이득이라고 생각됩니다 :) 현재 로직은 분리하더라도, 하위 Layer와 상위 Layer의 비즈니스 로직에 영향을 끼치는 부분이 없어, ControllerLayer 단위로 분리하면 걱정하시는 부분에 문제는 발생하지 않습니다.

Question 컴포넌트(또는 여러 도메인의 비즈니스 로직을 묶어주는 Controller 컴포넌트)를 분리할 경우, Portal 컴포넌트는 두 가지 역할을 담당하게 됩니다.
1. DOM 객체에 Portal 컴포넌트를 열어주는 역할
2. Modal component와 ThemeProvider를 추가해주는 역할. (사실 이 역할도 단일책임 원칙에 어긋납니다만 이 정도는 패스!)

---

## 관심사에 따라 컴포넌트를 분리한 코드
### Portal
- Portal 컴포넌트와 Modal을 관리하는 컴포넌트.
- 추후에 Modal이 열리고 닫히는 로직이 복잡해진다면, 이전 코드의 경우 하나의 컴포넌트에 여러 관심사가 공존하게 되어, 유지보수가 어려워짐.

```js
// Portal.js
import { useModal } from '../../hooks/useModal';
import { ThemeProvider } from 'styled-components';
import { ContentLayer } from '../경로';

export default function Portal() {
  const { isOpen, Modal, openModal, closeModal } = useModal();
  useEffect(() => {
    openModal();
  }, []);
  
 return (
    <>
      <ThemeProvider theme={darkTheme}>
        <Modal isOpen={isOpen} closeModal={closeModal}>
            <ModalWrapper>
              <ContentLayer />
            </ModalWrapper>
        </Modal>
      </ThemeProvider>
    </>
  );
}
```

### 2. ContentLayer (현재는 Question과 관련된 도메인밖에 존재하지 않음)

```js
// ContentLayer

export const ContentLayer = () => {
  
  // 타이머
  const { formattedTime, isActive, start } = useTimer(60 * 5);
  useEffect(() => {
    start();
  }, []);
  useEffect(() => {
    if (!isActive) {
      alert('시간이 초과되었습니다!');
      decrement();
    }
  }, [isActive]);

  // 1. 문제 랜덤으로 가져오기
  const [question, setQuestion] = useState<QuestionType | null>(null);
  const [isSubmitted, setIsSubmitted] = useState(false);
  useEffect(() => {
    setQuestion(getRandomQuestion(QuestionsData));
    setIsSubmitted(false);
  }, [isSubmitted]);

  // 2. 사용자 정답 작성 및 확인
  const { handleChange, isCorrect, answer } = useUserAnswer({ question });

  // 3. 사용자 라이프 감소
  // TODO : 전역으로 관리가 필요해 보임
  const { lifeCount, decrement } = useLife();

  const handleSubmit = () => {
    // 입력값이 없을 경우
    if (!answer) {
      alert('답을 입력해주세요!');
      return;
    }
    // 정답일 경우
    if (isCorrect) {
      alert('정답입니다!');
      setIsSubmitted(true);
    }
    // 오답일 경우
    if (!isCorrect) {
      alert('오답입니다!');
      decrement();
    }
  };
  
  return <>
          {question && (
              <Question formattedTime={formattedTime} closeModal={closeModal}>
                <Question.Question>{question.question}</Question.Question>
                <Question.Answer>
                  <Answer
                    question={question}
                    answer={answer}
                    handleChange={handleChange}
                  />
                </Question.Answer>
                <Question.Life>{lifeCount}</Question.Life>
                <Question.Submit>
                  <Button onClick={handleSubmit}>
                    <ButtonText>제출하기</ButtonText>
                  </Button>
                </Question.Submit>
              </Question>
          )}</>
}
```
추후 Question 뿐 아니라 여러 도메인이 추가되고, 각 도메인별로 state나 setter(비즈니스 로직)을 공유해야하는 상황이라면, 이전과 동일하게 ContentLayer에서 관리하면 됩니다!

```js
{question && (
            <ModalWrapper>
              <Question formattedTime={formattedTime} closeModal={closeModal}>
                <Question.Question>{question.question}</Question.Question>
                <Question.Answer>
                  <Answer
                    question={question}
                    answer={answer}
                    handleChange={handleChange}
                  />
                </Question.Answer>
                <Question.Life>{lifeCount}</Question.Life>
                <Question.Submit>
                  <Button onClick={handleSubmit}>
                    <ButtonText>제출하기</ButtonText>
                  </Button>
                </Question.Submit>
              </Question>
            </ModalWrapper>
          )}
```
현재 중괄호 내부의 로직은 Portal 컴포넌트에서 사용되는 useModal 및 ThemeProvider와 관심사가 다르며, 추후에 useModal의 열리고 닫힘 여부를 해당 Layer가 아닌 하위 Layer(ContentLayer)에서 정하게 되더라도, props를 통해 setter를 한 번만 전달만 해주면 됩니다! :)

요약: 상위 layer(컴포넌트) 객체의 역할이 `ThemeProvider`와 `Modal` 로직뿐인데 Life나 Question에 영향을 끼치는 변수 및 비즈니스 로직이 없고, 확장되더라도 props로 관리해도 될 정도로 결합도가 낮음!

2023-08-28 00:34 UTC, ww8007 commented on src/pages/content/components/Portal/Portal.tsx
> +  };
아 요런 이야기 였군요!
제가 이해를 잘못했네요... 너무나도 자세한 설명 감사드립니다 👍
저는 ContentLayer가 아닌 합성 컴포넌트 내부로 각각 비지니스 로직이 이동하는걸로 오해를 했어서
이 부분은 저도 전적으로 동의 합니다! 수정하도록 할게요.

2023-08-30 09:58 UTC, pengooseDev commented on src/pages/content/components/IconWrapper.tsx
> +};
그것도 좋을 것 같습니다. chlidren에 무엇이 들어올지 해당 컴포넌트(클래스)는 알지 못하고 서브 컴포넌트(서브클래스. 즉, 해당 컴포넌트를 import하여 사용하는 사용처)에 children에 주입(DI)할 컴포넌트(객체)를 위임하고 있습니다. 추가적인 비즈니스 로직 없이 현재의 결합도 정도를 유지한다면 ButtonContainer도 좋을 것 같습니다!
https://tecoble.techcourse.co.kr/post/2021-04-26-presentational-and-container/

2023-08-30 10:50 UTC, ww8007 commented on src/pages/content/components/IconWrapper.tsx
> +};
오 좋은 글 이네요 감사합니다! 수정했어요!

2023-09-01 15:17 UTC, pengooseDev approved these changes

2023-09-01 15:40 UTC, merged